SET statement_timeout = 0;

--==============================================================================
--bun:split

CREATE TABLE "admins" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "avatar" varchar NOT NULL,
    "email" varchar NOT NULL,
    "role" varchar NOT NULL,
    "password" bytea NOT NULL,
    "salt" varchar NOT NULL,
    "otp" bytea NOT NULL,
    "created" timestamptz NOT NULL,
    "updated" timestamptz NOT NULL
);

--bun:split

CREATE INDEX "admins_created_updated_idx" ON "admins" ("created", "updated");

--bun:split

CREATE UNIQUE INDEX "admins_email_unq" ON "admins" (lower("email"));
